version: '3.8'

services:
  web:
    build:
      context: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    depends_on:
      - db
    volumes:
      - ./flask_app:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
